import pdfreader
from pdfreader import PDFDocument, SimplePDFViewer
import argparse
import re

parser = argparse.ArgumentParser()
parser.add_argument('--doc', help='PDF Document to be parsed', dest='pdf_file')

args = parser.parse_args()
print(args.pdf_file)

file_d = open(args.pdf_file, 'rb')
pdf_document = PDFDocument(file_d)
viewer_document = SimplePDFViewer(file_d)

doc_pages = []

for index in range(13, len([p for p in pdf_document.pages()]) ):
#for index in range(13, 70):
    print('PAGE {}'.format(index))
    #starts parsing page by page
    viewer_document.navigate( index )
    viewer_document.render()

    regex_found = re.findall('\((.*?)\)', viewer_document.canvas.text_content)
    doc_pages.append( "".join(regex_found))

methods = []
commands = []
# now we can parse each page
for page in doc_pages:
   command =  re.findall('[0-9]\.[0-9]\.\s(AT\+\S*)\s',page) #ex: 2.2. AT+GMM
   if command:
       for item in command:
           commands.append(item)
       cd = re.findall('[0-9]\.[0-9]\.\sAT\+\S*\s(.*?)AT\+',page) #gets command description
       if cd:
            for name in cd:
                methods.append(name.strip().replace(' ','_').replace('(','_').replace(')','_'))


#re.findall('[0-9]\.[0-9]\.\s(AT\+\S*)\s',page) #ex: 2.2. AT+GMM 
#cm = re.findall('[0-9]\.[0-9]\.\sAT\+\S*\s(.*?)AT\+',page) #gets command description
#cm = re.findall('Test Command (.*?) \s*',page) #gets test command
    


filew = open('/home/cristianfunes/output.txt','w')
filew.write('// Autogenerated file \n')
for method, command in zip(methods, commands):
    filew.write('command_resp_t ' + method + '(command_t * send, commant_t * response); // ' + command + '\n')
    
file_d.close()
filew.close()

#document = open()
